### ISSUE TITLE
Is UAPI supported with Perl?

### ISSUE THREAD

**Issue by rwp0** [CpanelInc/cPanel-PublicAPI#38]
Is UAPI supported? I can't call many cPanel UAPI function using the `cpanel_api2_request` method.

For instance [create_database](https://documentation.cpanel.net/display/DD/UAPI+Functions+-+Mysql%3A%3Acreate_database) results in:

> cPanel::PublicAPI::cpanel_api2_request was called with the invalid API2 call of: Mysql::create_database

While the deprecated [MysqlFE::createdb](https://documentation.cpanel.net/display/DD/cPanel+API+2+Functions+-+MysqlFE%3A%3Acreatedb) works.

Can UAPI be called remotely as cPanel::PublicAPI from Perl? (I don't want to use the `uapi` command locally on a cPanel server)

Thanks.

**Comment by cpanelrikus** [comment]
cPanel::PublicAPI does not currently support UAPI. This makes it somewhat obsolete at the moment, as UAPI is the recommended cPanel API for most functions.

If you are already using cPanel::PublicAPI in your application and need to keep using it, you may be able to get it partially working with UAPI like this, as `api_request` is a generic method for any type of API or non-API query not explicitly supported by the module:

```
my $api = cPanel::PublicAPI->new( host => $server_hostname, user => $username, api_token => $api_token );
my ($status, $error, $json_scalar_ref) = $api->api_request( "cpanel", "/execute/Email/list_pops" );
```

You would then need to decode the JSON yourself, similar to what you would do after sending a request with LWP or HTTP::Tiny.

We do also ship the module Cpanel::RemoteAPI::cPanel with the product under the cPanel license (not open source, but source code provided), and this module provides similar functionality, but with UAPI support. However, third-party usage of internal modules to integrate with cPanel is potentially fragile as their interface is not subject to the same expectation of stability over time.

You've already indicated that local calls to the `uapi` utility aren't viable, so unless support for UAPI gets added to cPanel::PublicAPI, I would recommend either using the `api_request` method combined with an `/execute/...../.....` path (example above) or building your own client library.

**Comment by rwp0** [comment]
> cPanel::PublicAPI does not currently support UAPI. This makes it somewhat obsolete at the moment, as UAPI is the recommended cPanel API for most functions.
> 
> If you are already using cPanel::PublicAPI in your application and need to keep using it, you may be able to get it partially working with UAPI like this, as `api_request` is a generic method for any type of API or non-API query not explicitly supported by the module:
> 
> ```
> my $api = cPanel::PublicAPI->new( host => $server_hostname, user => $username, api_token => $api_token );
> my ($status, $error, $json_scalar_ref) = $api->api_request( "cpanel", "/execute/Email/list_pops" );
> ```
> 
> You would then need to decode the JSON yourself, similar to what you would do after sending a request with LWP or HTTP::Tiny.
> 
> We do also ship the module Cpanel::RemoteAPI::cPanel with the product under the cPanel license (not open source, but source code provided), and this module provides similar functionality, but with UAPI support. However, third-party usage of internal modules to integrate with cPanel is potentially fragile as their interface is not subject to the same expectation of stability over time.
> 
> You've already indicated that local calls to the `uapi` utility aren't viable, so unless support for UAPI gets added to cPanel::PublicAPI, I would recommend either using the `api_request` method combined with an `/execute/...../.....` path (example above) or building your own client library.

Thanks for the detailed explanation. I assume I won't be able to use the `Cpanel::RemoteAPI::cPanel` module remotely from my own machine having to execute the script locally on the cPanel server as with the `uapi` utility.

I don't like the `api_request` solution for it'd be too long for an API, but thanks for mentioning this, it's good to know that I can make use of it if needed to.


I just realized that the cPanel API 2 is actually not deprecated as with cPanel API 1, it's just not preferred to UAPI. I guess I have no other choice than to stick to it with using the `cPanel::PublicAPI` module which I like. It'd still be usable and current for the WHM API 1 at least I believe as it's that API is the only one of its kind.

Also is there a documentation (link to a page perhaps) on the reasoning why UAPI is recommended, and at what dates the cPanel API 2 is expected to be deprecated and obsoleted.

Would be good to know to compare the API's for an overview.


Thanks again, and I really appreciated your useful and detailed answer.

**Comment by cpanelrikus** [comment]
Some good news: I was informed by a colleague of the existence of cPanel::APIClient, which is maintained by cPanel and _does_ support UAPI queries:

- [cPanel::APIClient on MetaCPAN](https://metacpan.org/pod/cPanel::APIClient)
- [p5-cPanel-APIClient on GitHub](https://github.com/cpanel/p5-cPanel-APIClient)

Example:

```
my $api = cPanel::APIClient->create( service => "cpanel", transport => [ "HTTPSync", hostname => $hostname ], credentials => { username => $username, api_token => $api_token } );
my $response = $api->call_uapi( "Email", "list_pops" );
```

Although cPanel API 2 is not deprecated yet, UAPI has been the recommended choice for quite a while. To the best of my knowledge, no documentation exists detailing the specific technical reasons that UAPI is preferred over API 2.

Anecdotally, I can report that UAPI is a bit easier to work with when building HTTP-based queries for equivalent functions.

* API 2: `/json-api/cpanel?cpanel_jsonapi_module=Email&cpanel_jsonapi_func=listpops&cpanel_jsonapi_apiversion=2`
* UAPI: `/execute/Email/list_pops`

At this point, API 2 documentation only exists on our old documentation site [documentation.cpanel.net](https://documentation.cpanel.net/), and this website itself _is_ deprecated. Additionally, many of our cPanel API 2 documentation pages have a note at the top explaining that UAPI is preferred. We include this notice even if no equivalent UAPI function exists, as a general reminder to move in the direction of UAPI wherever possible.

Examples:

* [API 2 SSL::gencrt](https://documentation.cpanel.net/display/DD/cPanel+API+2+Functions+-+SSL%3A%3Agencrt) — `We strongly recommend that you use the following UAPI function instead of this function:` .......
* [API 2 Passwd::change_password](https://documentation.cpanel.net/display/DD/cPanel+API+2+Functions+-+Passwd%3A%3Achange_password) — `We strongly recommend that you use UAPI instead of cPanel API 2. However, no equivalent UAPI function exists.`

Right now there is no answer about when cPanel API 2 will be deprecated. When a concrete plan exists for cPanel API 2's deprecation, we will list it on the [cPanel Deprecation Plan](https://docs.cpanel.net/knowledge-base/cpanel-product/cpanel-deprecation-plan/) document. For reference, see the entry for cPanel API 1 that already appears there.

**Comment by rwp0** [comment]
Yes, I also saw `## DEPRECATED!` comments on many `api2_` functions such as `api2_listpops`.

Thanks for `cPanel::APIClient`, it's really good to know that I may refer to this distribution for UAPI calls.

I saw that PublicAPI is released more recently than APIClient on CPAN, so used that instead.

Moreover, having the two on different GitHub organizations ([CpanelInc](https://github.com/CpanelInc) and [cpanel](https://github.com/cpanel)) further contributed to the confusion.

Since as mentioned API 2 is also hidden under the [deprecated](https://documentation.cpanel.net/) documentation page, I'll consider it as semi-deprecated, and will try using UAPI in the future with the another module mentioned.

Thanks again for all the help @cpanelrikus ,  hope cPanel will never abandon Perl continuing the development and support of its current API's in it.

My concerns answered, I'm closing this issue.

**Comment by rwp0** [comment]
> We do also ship the module Cpanel::RemoteAPI::cPanel with the product under the cPanel license (not open source, but source code provided), and this module provides similar functionality, but with UAPI support. However, third-party usage of internal modules to integrate with cPanel is potentially fragile as their interface is not subject to the same expectation of stability over time.

Sorry @cpanelrikus but is there a documentation for the shipped `Cpanel::RemoteAPI::cPanel` and `Cpanel::RemoteAPI::WHM` modules? I couldn't find any searching in Google. I'm especially interested in using API tokens instead of the password if that's possible (But the only constructor method documented within the module is `new_from_password` it seems).

From my understanding, unlike `PublicAPI` and `APIClient` cPanel API distributions the `RemoteAPI` ships with cPanel source code, and we can use it locally within the server from Perl instead of shell scripting with `apitool` (which happens to be a binary file) aliases (such as `whmapi1` and `uapi`) importing from the cPanel's `#! /usr/local/cpanel/3rdparty/bin/perl` Perl.

Thanks.
